In [15]:
import sys
from pathlib import Path

def is_google_colab() -> bool:
    if "google.colab" in str(get_ipython()):
        return True
    return False

def clone_repository() -> None:
    !git clone https://github.com/featurestorebook/mlfs-book.git
    %cd mlfs-book

def install_dependencies() -> None:
    !pip install --upgrade uv
    !uv pip install --all-extras --system --requirement pyproject.toml

if is_google_colab():
    clone_repository()
    install_dependencies()
    root_dir = str(Path().absolute())
    print("Google Colab environment")
else:
    root_dir = Path().absolute()
    # Strip ~/notebooks/ccfraud from PYTHON_PATH if notebook started in one of these subdirectories
    if root_dir.parts[-1:] == ('airquality',):
        root_dir = Path(*root_dir.parts[:-1])
    if root_dir.parts[-1:] == ('notebooks',):
        root_dir = Path(*root_dir.parts[:-1])
    root_dir = str(root_dir) 
    print("Local environment")

# Add the root directory to the `PYTHONPATH` to use the `recsys` Python module from the notebook.
if root_dir not in sys.path:
    sys.path.append(root_dir)
print(f"Added the following directory to the PYTHONPATH: {root_dir}")
    
# Set the environment variables from the file <root_dir>/.env
from mlfs import config
#settings = config.HopsworksSettings(_env_file=f"{root_dir}/.env")

Local environment
Added the following directory to the PYTHONPATH: /Users/edvinramstrom/Documents/KTH/ID2223 Scalable/mlfs-book

<span style="font-width:bold; font-size: 3rem; color:#333;">- Part 02: Daily Feature Pipeline for Air Quality (aqicn.org) and weather (openmeteo)</span>

## 🗒️ This notebook is divided into the following sections:
1. Download and Parse Data
2. Feature Group Insertion


__This notebook should be scheduled to run daily__

In the book, we use a GitHub Action stored here:
[.github/workflows/air-quality-daily.yml](https://github.com/featurestorebook/mlfs-book/blob/main/.github/workflows/air-quality-daily.yml)

However, you are free to use any Python Orchestration tool to schedule this program to run daily.

### <span style='color:#ff5f27'> 📝 Imports

In [16]:
import datetime
import time
import requests
import pandas as pd
import hopsworks
from mlfs.airquality import util
from mlfs import config
import json
import os
import warnings
warnings.filterwarnings("ignore")

## <span style='color:#ff5f27'> 🌍 Get the Sensor URL, Country, City, Street names from Hopsworks </span>

__Update the values in the cell below.__

__These should be the same values as in notebook 1 - the feature backfill notebook__

In [17]:
project = hopsworks.login(engine="python")
fs = project.get_feature_store() 
secrets = hopsworks.get_secrets_api()

# This line will fail if you have not registered the AQICN_API_KEY as a secret in Hopsworks
AQICN_API_KEY = secrets.get_secret("AQICN_API_KEY").value
location_str = secrets.get_secret("SENSOR_LOCATION_JSON").value
location = json.loads(location_str)

country=location['country']
city=location['city']
street=location['street']
aqicn_url=location['aqicn_url']
latitude=location['latitude']
longitude=location['longitude']

today = datetime.date.today()


location_str

2025-11-13 17:34:08,194 INFO: Closing external client and cleaning up certificates.
Connection closed.
2025-11-13 17:34:08,197 INFO: Initializing external client
2025-11-13 17:34:08,197 INFO: Base URL: https://c.app.hopsworks.ai:443

2025-11-13 17:34:09,795 INFO: Python Engine initialized.

Logged in to project, explore it here https://c.app.hopsworks.ai:443/p/1298581

'{"country": "germany", "city": "stuttgart", "street": "arnulf-klett-platz", "aqicn_url": "https://api.waqi.info/feed/@11226", "latitude": "48.781080", "longitude": "9.183948"}'

### <span style="color:#ff5f27;"> 🔮 Get references to the Feature Groups </span>

In [18]:
# Retrieve feature groups
air_quality_fg = fs.get_feature_group(
    name='air_quality',
    version=3,
)
weather_fg = fs.get_feature_group(
    name='weather',
    version=2,
)

---

## <span style='color:#ff5f27'> 🌫 Retrieve Today's Air Quality data (PM2.5) from the AQI API</span>

In [19]:
import requests
import pandas as pd

aq_today_df = util.get_pm25(aqicn_url, country, city, street, today, AQICN_API_KEY)

lag_features = util.get_pm25_lagged_features(air_quality_fg, today, country, city, street)
for lag_name, lag_value in lag_features.items():
    aq_today_df[lag_name] = lag_value

# add day of week feature
aq_today_df['day_of_week'] = today.weekday()
# make int32
aq_today_df['day_of_week'] = aq_today_df['day_of_week'].astype('int32')

aq_today_df

Finished: Reading data from Hopsworks, using Hopsworks Feature Query Service (0.83s)

,pm25,country,city,street,date,url,pm25_lag1,pm25_lag2,pm25_lag3,day_of_week
0,73.0,germany,stuttgart,arnulf-klett-platz,2025-11-13,https://api.waqi.info/feed/@11226,51.0,49.0,52.0,3

In [20]:
aq_today_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   pm25         1 non-null      float32
 1   country      1 non-null      object
 2   city         1 non-null      object
 3   street       1 non-null      object
 4   date         1 non-null      datetime64[ns]
 5   url          1 non-null      object
 6   pm25_lag1    1 non-null      float32
 7   pm25_lag2    1 non-null      float32
 8   pm25_lag3    1 non-null      float32
 9   day_of_week  1 non-null      int32
dtypes: datetime64[ns](1), float32(4), int32(1), object(4)
memory usage: 188.0+ bytes

## <span style='color:#ff5f27'> 🌦 Get Weather Forecast data</span>

In [21]:
hourly_df = util.get_hourly_weather_forecast(city, latitude, longitude)
hourly_df = hourly_df.set_index('date')

# We will only make 1 daily prediction, so we will replace the hourly forecasts with a single daily forecast
# We only want the daily weather data, so only get weather at 12:00
daily_df = hourly_df.between_time('11:59', '12:01')
daily_df = daily_df.reset_index()
daily_df['date'] = pd.to_datetime(daily_df['date']).dt.date
daily_df['date'] = pd.to_datetime(daily_df['date'])
daily_df['city'] = city
daily_df

Coordinates 49.0°N 9.25°E
Elevation 245.0 m asl
Timezone None None
Timezone difference to GMT+0 0 s

,date,temperature_2m_mean,precipitation_sum,wind_speed_10m_max,wind_direction_10m_dominant,relative_humidity_2m_mean,surface_pressure_mean,city
0,2025-11-13,16.400000,0.0,6.130579,130.236282,60.0,987.323914,stuttgart
1,2025-11-14,16.549999,0.0,3.617955,95.710503,55.0,981.800659,stuttgart
2,2025-11-15,15.800000,0.0,0.509117,44.999897,71.0,981.144531,stuttgart
3,2025-11-16,13.500000,0.0,0.360000,360.000000,76.0,978.295166,stuttgart
4,2025-11-17,5.850000,0.3,12.481153,326.768280,91.0,981.981079,stuttgart
5,2025-11-18,5.000000,0.0,2.276840,161.564957,72.0,989.849304,stuttgart
6,2025-11-19,4.900000,0.0,4.213692,160.016800,76.0,979.163940,stuttgart

In [22]:
daily_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   date                         7 non-null      datetime64[ns]
 1   temperature_2m_mean          7 non-null      float32
 2   precipitation_sum            7 non-null      float32
 3   wind_speed_10m_max           7 non-null      float32
 4   wind_direction_10m_dominant  7 non-null      float32
 5   relative_humidity_2m_mean    7 non-null      float32
 6   surface_pressure_mean        7 non-null      float32
 7   city                         7 non-null      object
dtypes: datetime64[ns](1), float32(6), object(1)
memory usage: 408.0+ bytes

## <span style="color:#ff5f27;">⬆️ Uploading new data to the Feature Store</span>

In [23]:
# Insert new data
air_quality_fg.insert(aq_today_df)

2025-11-13 17:34:16,626 INFO: 	1 expectation(s) included in expectation_suite.
Validation succeeded.
Validation Report saved successfully, explore a summary at https://c.app.hopsworks.ai:443/p/1298581/fs/1286212/fg/1711467

Uploading Dataframe: 100.00% |██████████| Rows 1/1 | Elapsed Time: 00:01 | Remaining Time: 00:00

Launching job: air_quality_3_offline_fg_materialization
Job started successfully, you can follow the progress at
https://c.app.hopsworks.ai:443/p/1298581/jobs/named/air_quality_3_offline_fg_materialization/executions

(Job('air_quality_3_offline_fg_materialization', 'SPARK'),
 {
   "success": true,
   "results": [
     {
       "success": true,
       "expectation_config": {
         "expectation_type": "expect_column_min_to_be_between",
         "kwargs": {
           "column": "pm25",
           "min_value": -0.1,
           "max_value": 500.0,
           "strict_min": true
         },
         "meta": {
           "expectationId": 752664
         }
       },
       "result": {
         "observed_value": 73.0,
         "element_count": 1,
         "missing_count": null,
         "missing_percent": null
       },
       "meta": {
         "ingestionResult": "INGESTED",
         "validationTime": "2025-11-13T04:34:16.000626Z"
       },
       "exception_info": {
         "raised_exception": false,
         "exception_message": null,
         "exception_traceback": null
       }
     }
   ],
   "evaluation_parameters": {},
   "statistics": {
     "evaluated_expectations": 1,
     "successful_expectations": 1,
     "unsuccessful_expectations": 0,
     "success_percent": 100.0
   },
   "meta": {
     "great_expectations_version": "0.18.12",
     "expectation_suite_name": "aq_expectation_suite",
     "run_id": {
       "run_name": null,
       "run_time": "2025-11-13T17:34:16.626763+01:00"
     },
     "batch_kwargs": {
       "ge_batch_id": "98a4ae30-c0ae-11f0-9e61-6e1bd2fad6d7"
     },
     "batch_markers": {},
     "batch_parameters": {},
     "validation_time": "20251113T163416.626671Z",
     "expectation_suite_meta": {
       "great_expectations_version": "0.18.12"
     }
   }
 })

In [24]:
# Insert new data
weather_fg.insert(daily_df, wait=True)

2025-11-13 17:34:29,593 INFO: 	2 expectation(s) included in expectation_suite.
Validation succeeded.
Validation Report saved successfully, explore a summary at https://c.app.hopsworks.ai:443/p/1298581/fs/1286212/fg/1703359

Uploading Dataframe: 100.00% |██████████| Rows 7/7 | Elapsed Time: 00:01 | Remaining Time: 00:00

Launching job: weather_2_offline_fg_materialization
Job started successfully, you can follow the progress at
https://c.app.hopsworks.ai:443/p/1298581/jobs/named/weather_2_offline_fg_materialization/executions
2025-11-13 17:34:46,013 INFO: Waiting for execution to finish. Current state: SUBMITTED. Final status: UNDEFINED
2025-11-13 17:34:49,219 INFO: Waiting for execution to finish. Current state: RUNNING. Final status: UNDEFINED
2025-11-13 17:36:41,068 INFO: Waiting for execution to finish. Current state: AGGREGATING_LOGS. Final status: SUCCEEDED
2025-11-13 17:36:41,238 INFO: Waiting for log aggregation to finish.
2025-11-13 17:36:53,243 INFO: Execution finished successfully.

(Job('weather_2_offline_fg_materialization', 'SPARK'),
 {
   "success": true,
   "results": [
     {
       "success": true,
       "expectation_config": {
         "expectation_type": "expect_column_min_to_be_between",
         "kwargs": {
           "column": "wind_speed_10m_max",
           "min_value": -0.1,
           "max_value": 1000.0,
           "strict_min": true
         },
         "meta": {
           "expectationId": 747612
         }
       },
       "result": {
         "observed_value": 0.35999998450279236,
         "element_count": 7,
         "missing_count": null,
         "missing_percent": null
       },
       "meta": {
         "ingestionResult": "INGESTED",
         "validationTime": "2025-11-13T04:34:29.000593Z"
       },
       "exception_info": {
         "raised_exception": false,
         "exception_message": null,
         "exception_traceback": null
       }
     },
     {
       "success": true,
       "expectation_config": {
         "expectation_type": "expect_column_min_to_be_between",
         "kwargs": {
           "column": "precipitation_sum",
           "min_value": -0.1,
           "max_value": 1000.0,
           "strict_min": true
         },
         "meta": {
           "expectationId": 747613
         }
       },
       "result": {
         "observed_value": 0.0,
         "element_count": 7,
         "missing_count": null,
         "missing_percent": null
       },
       "meta": {
         "ingestionResult": "INGESTED",
         "validationTime": "2025-11-13T04:34:29.000593Z"
       },
       "exception_info": {
         "raised_exception": false,
         "exception_message": null,
         "exception_traceback": null
       }
     }
   ],
   "evaluation_parameters": {},
   "statistics": {
     "evaluated_expectations": 2,
     "successful_expectations": 2,
     "unsuccessful_expectations": 0,
     "success_percent": 100.0
   },
   "meta": {
     "great_expectations_version": "0.18.12",
     "expectation_suite_name": "weather_expectation_suite",
     "run_id": {
       "run_name": null,
       "run_time": "2025-11-13T17:34:29.593478+01:00"
     },
     "batch_kwargs": {
       "ge_batch_id": "a05f5094-c0ae-11f0-9e61-6e1bd2fad6d7"
     },
     "batch_markers": {},
     "batch_parameters": {},
     "validation_time": "20251113T163429.593409Z",
     "expectation_suite_meta": {
       "great_expectations_version": "0.18.12"
     }
   }
 })

## <span style="color:#ff5f27;">⏭️ **Next:** Part 03: Training Pipeline
 </span> 

In the following notebook you will read from a feature group and create training dataset within the feature store